# Generated by Django 4.2.13 on 2024-06-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='player_one_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='player_two_win',
            field=models.BooleanField(default=False),
        ),
    ]
