# Generated by Django 4.2.13 on 2024-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game2', '0003_stats_player_two_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='player_two_avatar',
            field=models.ImageField(blank=True, default='static/avatars/default.jpg', upload_to='static/avatars/'),
        ),
    ]
