# Generated by Django 4.2.13 on 2024-06-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game2', '0004_stats_player_two_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='player_two_avatar',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_two_displayname',
        ),
    ]
