# Generated by Django 4.2.13 on 2024-06-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game2', '0006_stats_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='tournament_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
