# Generated by Django 4.2.13 on 2024-07-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_List',
            fields=[
                ('tournament', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=50)),
                ('player1', models.EmailField(max_length=254)),
                ('player2', models.EmailField(max_length=254)),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament_list')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament_list')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Connected_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=50)),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament_list')),
            ],
        ),
    ]
