# Generated by Django 4.2.13 on 2024-06-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_List',
            fields=[
                ('tournament', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Connected_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament_list')),
            ],
        ),
    ]
