# Generated by Django 4.2.13 on 2024-06-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament_list')),
            ],
        ),
    ]
