# Generated by Django 4.2.13 on 2024-06-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=50)),
                ('player1', models.EmailField(max_length=254)),
                ('player2', models.EmailField(max_length=254)),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament_list')),
            ],
        ),
    ]
