# Generated by Django 4.2.13 on 2024-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_play',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
