# Generated by Django 4.2.13 on 2024-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournament_play_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_connected_users',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament_connected_users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tournament_play',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
    ]
