# Generated by Django 4.2.13 on 2024-05-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0015_alter_user_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRooms',
            fields=[
                ('room_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateRooms',
            fields=[
                ('private_room_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailto', models.EmailField(max_length=254)),
                ('displaynameto', models.CharField(max_length=50)),
                ('emailfrom', models.EmailField(max_length=254)),
                ('displaynamefrom', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('private_room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.privaterooms')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('displayname', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms')),
            ],
        ),
        migrations.CreateModel(
            name='Connected_Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=50, unique=True)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms')),
            ],
        ),
        migrations.CreateModel(
            name='Blocked_Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=50, unique=True)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
