# Generated by Django 4.2.11 on 2024-05-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatrooms_alter_connected_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connected_users',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms'),
        ),
    ]
