# Generated by Django 4.2.11 on 2024-05-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_user_displayname'),
        ('chat', '0003_alter_connected_users_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=50, unique=True)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
