# Generated by Django 4.2.11 on 2024-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_privatemessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessages',
            name='displayname',
        ),
        migrations.RemoveField(
            model_name='privatemessages',
            name='email',
        ),
        migrations.RemoveField(
            model_name='privatemessages',
            name='user',
        ),
        migrations.AddField(
            model_name='privatemessages',
            name='displaynameto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privatemessages',
            name='emailto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='privatemessages',
            name='private_room_name',
            field=models.CharField(default='default_room_name', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='displaynamefrom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='emailfrom',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
