# Generated by Django 4.2.11 on 2024-05-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_privatemessages_displaynamefrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRooms',
            fields=[
                ('room_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='privatemessages',
            name='private_room_name',
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.privaterooms'),
        ),
    ]
