# Generated by Django 4.2.11 on 2024-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_privaterooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privaterooms',
            name='room_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
