# Generated by Django 4.2.11 on 2024-05-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_privaterooms_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessages',
            name='private_room_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.privaterooms'),
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms'),
        ),
    ]
