# Generated by Django 4.2.11 on 2024-05-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_privatemessages_private_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessages',
            name='private_room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.privaterooms'),
        ),
    ]
