# Generated by Django 4.2.13 on 2024-05-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_privatemessages_private_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='privaterooms',
            name='private_room_name',
            field=models.CharField(default='default_value', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='privaterooms',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatrooms'),
        ),
    ]
