# Generated by Django 4.2.13 on 2024-06-17 11:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_score', models.IntegerField()),
                ('player_one_hits', models.IntegerField()),
                ('player_one_aces', models.IntegerField()),
                ('player_one_win', models.BooleanField(default=False)),
                ('player_two', models.EmailField(max_length=254)),
                ('player_two_score', models.IntegerField()),
                ('player_two_hits', models.IntegerField()),
                ('player_two_aces', models.IntegerField()),
                ('player_two_win', models.BooleanField(default=False)),
                ('match_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('point_length', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), default=list, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game5_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
