# Generated by Django 4.2.13 on 2024-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='tournament',
            field=models.BooleanField(default=False),
        ),
    ]
