# Generated by Django 4.2.13 on 2024-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game5', '0002_stats_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='player_one_tournament_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='player_two_tournament_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='tournament_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
