services:
  postgresql:
    container_name: postgresql
    build: ./requirements/postgresql
    volumes:
      - data_db:/var/lib/postgresql
    restart: always
    networks:
      - db
    env_file:
      - .env
    expose:
      - '5432:5432'
    stdin_open: true 
    tty: true
  django:
    container_name: django
    build: ./requirements/django
    volumes:
      - data_django:/pong
    restart: always
    networks:
      - db
      - django
    env_file:
      - .env
    expose:
      - '8000:8000'
    ports:
      - '22:22'
    depends_on:
      - postgresql
    stdin_open: true 
    tty: true  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - data_django:/pong
    restart: always
    networks:
       - django
    env_file:
      - .env
    ports:
      - '80:80'
    depends_on:
      - django
    stdin_open: true 
    tty: true  
volumes:
  data_db:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/postgresql
      o: bind
  data_django:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/django
      o: bind
 
networks:
  db:
    driver: bridge
  django:
    driver: bridge
  
  