# Generated by Django 4.2.14 on 2024-07-19 14:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player_score', models.IntegerField()),
                ('left_player_hits', models.IntegerField()),
                ('left_player_aces', models.IntegerField()),
                ('left_player_win', models.BooleanField(default=False)),
                ('right_player', models.EmailField(max_length=254)),
                ('right_player_score', models.IntegerField()),
                ('right_player_hits', models.IntegerField()),
                ('right_player_aces', models.IntegerField()),
                ('right_player_win', models.BooleanField(default=False)),
                ('match_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('point_length', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), default=list, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tournament', models.BooleanField(default=False)),
            ],
        ),
    ]
