# Generated by Django 4.2.13 on 2024-06-03 11:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player_score', models.IntegerField()),
                ('left_player_hits', models.IntegerField()),
                ('left_player_aces', models.IntegerField()),
                ('right_player', models.EmailField(max_length=254)),
                ('right_player_score', models.IntegerField()),
                ('right_player_hits', models.IntegerField()),
                ('right_player_aces', models.IntegerField()),
                ('match_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('point_length', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), default=list, size=None)),
                ('left_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
