# Generated by Django 4.2.13 on 2024-06-03 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stats',
            name='left_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game3_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
