# Generated by Django 4.2.13 on 2024-06-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game3', '0002_stats_created_at_alter_stats_left_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='left_player_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='right_player_win',
            field=models.BooleanField(default=False),
        ),
    ]
