# Generated by Django 4.2.11 on 2024-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(help_text='Your email', max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('displayname', models.CharField(max_length=20, verbose_name='Display Name')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='Avatar')),
            ],
        ),
    ]
