# Generated by Django 4.2.11 on 2024-04-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayname',
            field=models.CharField(max_length=20, unique=True, verbose_name='Display Name'),
        ),
    ]
