# Generated by Django 4.2.13 on 2024-05-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sessionid',
        ),
        migrations.AddField(
            model_name='user',
            name='tokenid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
