# Generated by Django 4.2.13 on 2024-05-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_sessionid_user_tokenid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokenid',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
