# Generated by Django 4.2.11 on 2024-04-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sessionid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
