# Generated by Django 4.2.11 on 2024-04-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sessionid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
