# Generated by Django 4.2.11 on 2024-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_password_alter_user_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email'),
        ),
    ]
