# Generated by Django 4.2.11 on 2024-04-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_securitycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fourtwo',
            field=models.BooleanField(default=False),
        ),
    ]
