# Generated by Django 4.2.11 on 2024-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_fourtwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fourtwo',
            field=models.BooleanField(default=True),
        ),
    ]
