# Generated by Django 4.2.11 on 2024-04-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_fourtwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fourtwo',
        ),
        migrations.AddField(
            model_name='user',
            name='fourtytwo',
            field=models.BooleanField(default=False),
        ),
    ]
