# Generated by Django 4.2.11 on 2024-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_user_fourtwo_user_fourtytwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fourtytwo',
        ),
        migrations.AddField(
            model_name='user',
            name='fourtwo',
            field=models.BooleanField(default=False),
        ),
    ]
