# Generated by Django 4.2.11 on 2024-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_user_fourtwo_user_fourtytwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Display Name'),
        ),
    ]
